name: 'Update DB for Repo'
description: 'Update DB for Repo in Releases'
branding:
  icon: user-check
  color: gray-dark
inputs:
  name:
    description: 'REPO の呼び方はこちらへ'
    required: true
    default: 'zhaose-repo'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ env.GITHUB_REPOSITORY }}
    - ${{ inputs.repo-name }}
